version: '3.8'

services:
# -----------------------
# Backend service
# -----------------------
  backend:
    container_name: app_backend
    build:
      context: ./be
      dockerfile: Dockerfile.be
    ports:
      - "8080:8080"
    env_file:
      - ./be/.env 
    restart: always
# -----------------------
# Frontend service
# -----------------------
  frontend:
    container_name: app_frontend
    build:
      context: ./fe
      dockerfile: Dockerfile.fe
    ports:
      - "80:80"
    depends_on:
      - backend
    env_file:
      - ./fe/.env
    restart: always
